### ISSUE TITLE
[bug] 几乎所有 TTL 都是 300

### ISSUE THREAD

**Issue by SpaceTimee** [ccbikai/DNS.Surf#5]
https://dns.surf 的搜索结果中大部分 TTL 都是 300，这是在无法获取到 TTL 时默认省缺的数值吗，还是什么 Bug 引起的

**Comment by miantiao-me** [comment]
DNS 的 TTL 一般都设置 300。如果是冷门域名使用的人少，就无法命中缓存， 实时查询就是 300 了。

你可以试一下 GitHub.com ，就发现不一致了 https://dns.surf/?name=github.com&type=A&resolver=cloudflare
